import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "./responsive.css";
import Provider from "@/provider";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
